spring:
  application:
    name: transfer-api
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create   # 개발 단계에서는 create/update, 운영은 validate/none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: true

logging:
  level:
    org.springframework.kafka: INFO

id:
  snowflake:
    node-id: ${SNOWFLAKE_NODE_ID:1}
    custom-epoch: 1704067200000
    max-clock-backward-ms: 5
