spring:
  application:
    name: transfer-api
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.kafka: INFO

id:
  snowflake:
    node-id: ${SNOWFLAKE_NODE_ID:1}
    custom-epoch: 1704067200000
    max-clock-backward-ms: 5

app:
  relay:
    enabled: false
  transfer.topic: transfer.events.v1