spring:
  application:
    name: fds-consumer
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none   # 개발 단계에서는 create/update, 운영은 validate/none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: fds-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "io.github.hyungkishin.transentia.*"
    listener:
      ack-mode: manual
      type: single

app:
  transfer:
    topic: transfer.events.v1
  retry:
    topic: transfer.events.retry.v1
  dlq:
    topic: transfer.events.dlq.v1

logging:
  level:
    org.springframework.kafka: INFO
    io.github.hyungkishin.transentia: DEBUG
