spring:
  application:
    name: transfer-relay

  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 30000

server:
  port: 8081

kafka-config:
  bootstrap-servers: host.docker.internal:9094
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8085
  num-of-partitions: 3
  replication-factor: 1

kafka-producer-config:
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  compressionType: lz4
  acks: "1"
  batchSize: 65536        # 64KB로 증가
  batchSizeBoostFactor: 1
  lingerMs: 5             # 배치 대기 시간
  requestTimeoutMs: 1000  # 1초로 단축
  retryCount: 0           # 재시도 없음 (빠른 실패)

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  consumer-group-id: fds-consumer-group
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 8
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

app:
  outbox:
    relay:
      batchSize: 500
      fixedDelayMs: 1000
      initialDelayMs: 5000
      timeoutSeconds: 10
      threadPoolSize: 4
      baseBackoffMs: 5000
      maxBackoffMs: 600000
      slowProcessingThresholdMs: 3000
      
      # 파티셔닝 설정 (환경변수로 주입)
      instanceId: ${RELAY_INSTANCE_ID:0}
      totalInstances: ${RELAY_TOTAL_INSTANCES:1}

  kafka:
    topics:
      transfer-events: transfer-transaction-events

management:
  tracing:
    enabled: false